/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: b44cb7ef4589507a1c77fca017a6456b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "GeenieAgent";
	}
	interface Env {
		OPENAI_API_KEY: string;
		GeenieAgent: DurableObjectNamespace<import("./src/server/index").GeenieAgent>;
		VECTORIZE: VectorizeIndex;
		BROWSER: Fetcher;
		AI: Ai;
		CRAWL_OPENSTREETMAP_WIKI_TAGS: Workflow<Parameters<import("./src/server/index").CrawlOpenStreetMapWikiTagsWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> {}
}
